#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
wired &
#tint2 &
sh $HOME/.config/polybar/launch.sh &
source $HOME/.cache/wal/colors.sh

#bspc monitor -d I II III IV V
bspc monitor -d 1 2 3 4 5
#bspc monitor -d          

bspc config border_width 20
bspc config window_gap 20
bspc config focus_follows_pointer true
bspc config pointer_motion_interval 40

bspc config split_ratio 0.5
bspc config borderless_monocle false
bspc config gapless_monocle false

bspc config normal_border_color "$background"
bspc config focused_border_color "$background"
source $HOME/.config/bspwm/3bs

bspc rule -a '*' state=floating border=off
bspc rule -a URxvt state=tiled follow=on
bspc rule -a Alacritty state=tiled follow=on
bspc rule -a krita state=tiled follow=on
bspc rule -a firefox-developer-edition state=tiled
bspc rule -a helvum state=tiled
bspc rule -a qutebrowser state=tiled
bspc rule -a mercury-default state=tiled
bspc rule -a Lutris state=tiled
bspc rule -a Conky layer=above state=floating
